# Generated by Django 3.0.14 on 2022-08-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Best')]),
        ),
    ]
